### ISSUE TITLE
Not working with Twig template engine.

### ISSUE THREAD

**Issue by blizzardofozz** [upscalesoftware/swoole-session#1]
Hi,
Should swoole-session be working with Swoole 4.5.2, PHP 7.4.3?

This is what I'm getting:
```
PHP Warning:  session_id(): Cannot change session id when headers already sent in /var/www/html/mvc_swoole/vendor/upscale/swoole-session/src/SessionMiddleware.php on line 62
PHP Warning:  session_start(): Cannot start session when headers already sent in /var/www/html/mvc_swoole/vendor/upscale/swoole-session/src/SessionMiddleware.php on line 63
PHP Warning:  session_id(): Cannot change session id when headers already sent in /var/www/html/mvc_swoole/vendor/upscale/swoole-session/src/SessionMiddleware.php on line 80
```

Regards.

**Comment by sshymko** [comment]
@blizzardofozz 
Your application is probably sending the output directly (via `echo`, `print`, `fwrite(STDOUT)`, `include $templatePhtml`, etc.) which is incompatible with the PHP sessions as noted in the docs:
> Direct output bypassing Swoole response is prohibited. Writing to the standard output stream violates the `headers_sent()` requirement of the PHP session functions.

Make sure to send the response via the Swoole response instance `\Swoole\Http\Response`.

**Comment by blizzardofozz** [comment]
I'm using Twig. 

`$this->response->end(View::renderTemplate('twig_file.html');`

`public static function renderTemplate(string $template, array $args = []): string {
...
return $twig->render($template, $args);
}`


Otherwise, it is working, if: $response->end('html with session output'); Just checked.

**Comment by sshymko** [comment]
@blizzardofozz,
You'd have to use the output buffering, for example:
```php
ob_start();
$output = View::renderTemplate('twig_file.html');
ob_end_clean();
$response->end($output);
```

It is suspicious that Twig generates standard output. It should be buffering the output and returning it. Something is wrong with the Twig implementation or its use by the View layer.

**Comment by blizzardofozz** [comment]
This is what I'm doing. The first time I click the link for the second page it works but if I click the link to the index page it breaks:

```php
defined('DS') ? null : define('DS', DIRECTORY_SEPARATOR);
require 'vendor/autoload.php';
use Upscale\Swoole\Session\SessionMiddleware;

function indexPage($response) {
    $_SESSION['data'] = 'data';
    $response->header("Content-Type", "text/html");
    $response->end("<html><h1>Hello World</h1><a href=\"second\">page two</a></html>");
}

function secondPage($response) {
    $loader = new \Twig\Loader\FilesystemLoader('.' . DS . 'views');
    $twig = new \Twig\Environment($loader);
    $response->header("Content-Type", "text/html");
    ob_start();
    $output = $twig->render('second.html', [ 'data' => $_SESSION['data'] ?? '' ]);
    ob_end_clean();
    $response->end($output);
}

$server = new Swoole\HTTP\Server("127.0.0.1", 9501);
$server->on("start", function (Swoole\Http\Server $server) {
    echo "Swoole http server is started at http://127.0.0.1:9501\n";
});

$server->on("request", new SessionMiddleware(function($request, $response) {
    if ($request->server['request_uri'] === '/') {
        indexPage($response);
    }

    if ($request->server['request_uri'] === '/second') {
        secondPage($response);
    }
}));
$server->start();
```

**Comment by sshymko** [comment]
It seems to be the Swoole output buffering bug [#1828](https://github.com/swoole/swoole-src/issues/1828) fixed long ago is reproducible again.

```php
<?php

$server = new Swoole\HTTP\Server('127.0.0.1', 9501);
$server->set([
    'worker_num' => 1,
]);
$server->on('request', function($request, $response) {
    ob_start();
//    echo "Test";
    ob_end_clean();
    $response->end("headers_sent=" . (int)headers_sent() . "\n");
});
$server->start();
```

```bash
curl http://127.0.0.1:9501/
headers_sent=0

curl http://127.0.0.1:9501/
headers_sent=1
```

**Comment by sshymko** [comment]
Reported the failing test case to Swoole [#3552](https://github.com/swoole/swoole-src/pull/3552).

**Comment by sshymko** [comment]
@blizzardofozz 
Narrowed down the issue to be only reproducible with the coroutines enabled (they're enabled by default).
The workaround is to turn them OFF which should be done anyways to safely access the global variable `$_SESSION`.

**The workaround:**
```php
$server->set([
    'enable_coroutine' => false,
]);
```

Will update the documentation accordingly.

**Comment by blizzardofozz** [comment]
Thank you, it works this way.

**Comment by sshymko** [comment]
@blizzardofozz 
Glad to help. Thanks for reporting this issue! Much appreciated.
