### ISSUE TITLE
Compatibility with openswoole

### ISSUE THREAD

**Issue by attisan** [upscalesoftware/swoole-session#3]
Could this be compatible with openswoole? atm composer complains about the missing extension when using openswoole.

**Comment by sshymko** [comment]
@attisan 
The implementation should be compatible with both `swoole` and `openswoole`. Inability to install via Composer highlights a problem with an unfortunate split of the Swoole project. In Composer, there's no way to declare dependencies to require either one extension or the other.

The workaround is to install ignoring the platform requirement:
```bash
composer install --ignore-platform-req=ext-swoole
```

**Comment by sshymko** [comment]
@attisan 
The workaround to installing any `ext-swoole` dependencies is to declare the following in your project's `composer.json`:
```json
{
    "replace": {
        "ext-swoole": "*"
    }
}
```

After that you'll be able to `composer install` normally.

I'm working on providing openswoole support. Meanwhile, please use the workaround above.
